"""creacion inicial

Revision ID: 350bd93fc398
Revises: 
Create Date: 2026-10-02 10:01:36.335155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350bd93fc398'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena_hasheada', sa.String(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gimnasios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_gimnasio', sa.String(), nullable=True),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('color_hex', sa.String(), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Enum('dueno', 'recepcionista', 'profesor', 'alumno', name='nombreroles'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PagosGimnasios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gimnasio_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.Column('metodo_pago', sa.String(), nullable=False),
    sa.Column('nota', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gimnasio_id'], ['gimnasios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_plan', sa.String(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('dias_duracion', sa.Integer(), nullable=True),
    sa.Column('gimnasio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gimnasio_id'], ['gimnasios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena_hasheada', sa.String(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.Column('gimnasio_id', sa.Integer(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gimnasio_id'], ['gimnasios.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_asistencia', sa.DateTime(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('gimnasio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['gimnasio_id'], ['gimnasios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IngresoGimnasio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('gimnasio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['gimnasio_id'], ['gimnasios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MarcasPersonales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_nombre', sa.String(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('gimnasio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gimnasio_id'], ['gimnasios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('gimnasio_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['gimnasio_id'], ['gimnasios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rutinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rutina', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.Column('gimnasio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['gimnasio_id'], ['gimnasios.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejercicios', sa.String(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('rutina_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ejercicios')
    op.drop_table('rutinas')
    op.drop_table('Pagos')
    op.drop_table('MarcasPersonales')
    op.drop_table('IngresoGimnasio')
    op.drop_table('Asistencias')
    op.drop_table('usuarios')
    op.drop_table('Planes')
    op.drop_table('PagosGimnasios')
    op.drop_table('roles')
    op.drop_table('gimnasios')
    op.drop_table('Administradores')
    # ### end Alembic commands ###
