"""Creacion tabla soporte

Revision ID: dc98be2d2b5a
Revises: 350bd93fc398
Create Date: 2026-10-07 10:54:21.493215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc98be2d2b5a'
down_revision: Union[str, Sequence[str], None] = '350bd93fc398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConsultasSoporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gimnasio_id', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=False),
    sa.Column('esta_resuelto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gimnasio_id'], ['gimnasios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ConsultasSoporte')
    # ### end Alembic commands ###
